### ISSUE TITLE
Deleted polygon still able to be highlighted

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/BLTAdmin_angular#2]
A test polygon located on the Venezuela/Brasil border disappeared after edits were saved. It will still become highlighted by manually selecting the area.

**Comment by venikunche** [comment]
When you click on the map, Leaflet identifies the latitude and longitude and finds the pulas in that area. However, it seems to return multiple pulas in different layers even if there is supposed to be only one. For eg. for one of the PULAs, even though it is supposed to be only in the effective layer, it returns multiple features for this PULA on different layers when I click on it. I think this has something to do with how the pulas are setup in ArcGIS. 

I wrote extra the logic to filter out and show only the visible pulas.
