### ISSUE TITLE
Browser Popup with wrong password

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/BLTAdmin_angular#3]
The browser shows a popup when you enter an incorrect username and/or password.

**Comment by HansVraga** [comment]
@troddick remember what IIS setting this was?

**Comment by venikunche** [comment]
@troddick and @HansVraga: I went and checked all of the IIS settings. Form authentication was enabled for the application and sub applications. I thought to enable it for BLTServices too. That seems to have solved the issue.
